name: FastAPI Workflow

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Verify Python version
      run: python --version

    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Set Poetry to use Python 3.12
      run: poetry env use python3.12

    - name: List project files
      run: ls -al

    - name: Cache poetry dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-cache-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-cache-

    - name: Install Python dependencies
      run: poetry install --no-interaction

    - name: Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project. Run poetry env use python3.12
